---
title: "Class 12: Structural Bioinformatics 1"
author: "Seth McNeely"
date: "2/13/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Section 1: Inroduction to the RCSB Protein Data Bank (PDB)

### 1.1 PDB Statistics

> Q1: Determine the percentage of structures solved by X-Ray and EM. Determine what proportion of structures are proteins.

```{r}
# Read in file
stats <- read.csv("Data Export Summary.csv", row.names = 1)

# Calculate percentage of solved by each method
solvedByMethod <- stats$Total / sum(stats$Total) * 100
names(solvedByMethod) <- rownames(stats)
round(solvedByMethod, 2)
```

```{r}
round(sum(stats$Proteins / sum(stats$Total) * 100), 2)
```

> Q2: Determine how many HIV-1 protease structures are in the current PDB.

141 as of 2/13/20

## Section 2: Visualizing the HIV-1 protease structure

### 2.2 Using Atom Selections


## g

```{r}
library(bio3d)

pdb <- read.pdb("1hsg")
pdb
```

```{r}
protein <- atom.select(pdb, string="protein", value=TRUE)
ligand <- atom.select(pdb, string="ligand", value=TRUE)
```

```{r}
write.pdb(protein, file="1hsg_protein.pdb")
write.pdb(ligand, file="1hsg_ligand.pdb")
```

